{"totalCount":36,"grade":"E","repositories":[{"url":"https://github.com/MTES-MCT/carbure","vulnerabilityAlerts":{"totalCount":36,"nodes":[{"dismissedAt":null,"createdAt":"2024-05-21T08:33:15Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"requests"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9wx4-h78v-vm56"},{"type":"CVE","value":"CVE-2024-35195"}],"references":[{"url":"https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"},{"url":"https://github.com/psf/requests/pull/6655"},{"url":"https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"},{"url":"https://github.com/advisories/GHSA-9wx4-h78v-vm56"}]}}},{"dismissedAt":null,"createdAt":"2024-06-26T19:31:00Z","securityVulnerability":{"severity":"LOW","package":{"name":"djangorestframework"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-gw84-84pc-xp82"},{"type":"CVE","value":"CVE-2024-21520"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-21520"},{"url":"https://github.com/encode/django-rest-framework/pull/9435"},{"url":"https://github.com/encode/django-rest-framework/commit/3b41f0124194430da957b119712978fa2266b642"},{"url":"https://security.snyk.io/vuln/SNYK-PYTHON-DJANGORESTFRAMEWORK-7252137"},{"url":"https://github.com/encode/django-rest-framework/compare/3.15.1...3.15.2"},{"url":"https://github.com/advisories/GHSA-gw84-84pc-xp82"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:03:08Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9jmf-237g-qf46"},{"type":"CVE","value":"CVE-2024-39330"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39330"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/2b00edc0151a660d1eb86da4059904a0fc4e095e"},{"url":"https://github.com/django/django/commit/9f4f63e9ebb7bf6cb9547ee4e2526b9b96703270"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-58.yaml"},{"url":"https://github.com/advisories/GHSA-9jmf-237g-qf46"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:04:28Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qg2p-9jwr-mmqf"},{"type":"CVE","value":"CVE-2024-38875"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-38875"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/7285644640f085f41d60ab0c8ae4e9153f0485db"},{"url":"https://github.com/django/django/commit/79f368764295df109a37192f6182fb6f361d85b5"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-56.yaml"},{"url":"https://github.com/advisories/GHSA-qg2p-9jwr-mmqf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:04:53Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-x7q2-wr7g-xqmf"},{"type":"CVE","value":"CVE-2024-39329"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39329"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b"},{"url":"https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml"},{"url":"https://github.com/advisories/GHSA-x7q2-wr7g-xqmf"}]}}},{"dismissedAt":null,"createdAt":"2024-07-10T22:05:27Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-f6f8-9mx6-9mx2"},{"type":"CVE","value":"CVE-2024-39614"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39614"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/jul/09/security-releases"},{"url":"https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3"},{"url":"https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml"},{"url":"https://github.com/advisories/GHSA-f6f8-9mx6-9mx2"}]}}},{"dismissedAt":null,"createdAt":"2024-07-18T18:17:04Z","securityVulnerability":{"severity":"LOW","package":{"name":"sentry-sdk"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-g92j-qhmh-64v2"},{"type":"CVE","value":"CVE-2024-40647"}],"references":[{"url":"https://github.com/getsentry/sentry-python/security/advisories/GHSA-g92j-qhmh-64v2"},{"url":"https://github.com/getsentry/sentry-python/pull/3251"},{"url":"https://github.com/getsentry/sentry-python/commit/763e40aa4cb57ecced467f48f78f335c87e9bdff"},{"url":"https://docs.python.org/3/library/subprocess.html"},{"url":"https://docs.sentry.io/platforms/python/integrations/default-integrations"},{"url":"https://docs.sentry.io/platforms/python/integrations/default-integrations/#stdlib"},{"url":"https://github.com/getsentry/sentry-python/releases/tag/2.8.0"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-40647"},{"url":"https://github.com/advisories/GHSA-g92j-qhmh-64v2"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:19:33Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jh75-99hh-qvx9"},{"type":"CVE","value":"CVE-2024-41989"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41989"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/27900fe56f3d3cabb4aeb6ccb82f92bab29073a8"},{"url":"https://github.com/django/django/commit/fc76660f589ac07e45e9cd34ccb8087aeb11904b"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-67.yaml"},{"url":"https://github.com/advisories/GHSA-jh75-99hh-qvx9"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:19:51Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-795c-9xpc-xw6g"},{"type":"CVE","value":"CVE-2024-41990"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41990"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/7b7b909579c8311c140c89b8a9431bf537febf93"},{"url":"https://github.com/django/django/commit/d0a82e26a74940bf0c78204933c3bdd6a283eb88"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-68.yaml"},{"url":"https://github.com/advisories/GHSA-795c-9xpc-xw6g"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:20:17Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-pv4p-cwwg-4rph"},{"type":"CVE","value":"CVE-2024-42005"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-42005"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/32ebcbf2e1fe3e5ba79a6554a167efce81f7422d"},{"url":"https://github.com/django/django/commit/f4af67b9b41e0f4c117a8741da3abbd1c869ab28"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-70.yaml"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://github.com/advisories/GHSA-pv4p-cwwg-4rph"}]}}},{"dismissedAt":null,"createdAt":"2024-08-07T19:20:44Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-r836-hh6v-rg5g"},{"type":"CVE","value":"CVE-2024-41991"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-41991"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/aug/06/security-releases"},{"url":"https://github.com/django/django/commit/523da8771bce321023f490f70d71a9e973ddc927"},{"url":"https://github.com/django/django/commit/efea1ef7e2190e3f77ca0651b5458297bc0f6a9f"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-69.yaml"},{"url":"https://github.com/advisories/GHSA-r836-hh6v-rg5g"}]}}},{"dismissedAt":null,"createdAt":"2024-10-04T16:37:28Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"@sentry/browser"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-593m-55hh-j8gv"}],"references":[{"url":"https://github.com/getsentry/sentry-javascript/security/advisories/GHSA-593m-55hh-j8gv"},{"url":"https://github.com/getsentry/sentry-javascript/pull/13838"},{"url":"https://github.com/getsentry/sentry-javascript/commit/35bdc87dee3498794e34c1ad35dd9927950c8766"},{"url":"https://github.com/getsentry/sentry-javascript/releases/tag/8.33.0"},{"url":"https://github.com/getsentry/sentry-javascript/releases/tag/7.119.1"},{"url":"https://github.com/advisories/GHSA-593m-55hh-j8gv"}]}}},{"dismissedAt":null,"createdAt":"2024-10-07T10:29:03Z","securityVulnerability":{"severity":"LOW","package":{"name":"cookie"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-pxg6-pf52-xh8x"},{"type":"CVE","value":"CVE-2024-47764"}],"references":[{"url":"https://github.com/jshttp/cookie/security/advisories/GHSA-pxg6-pf52-xh8x"},{"url":"https://github.com/jshttp/cookie/pull/167"},{"url":"https://github.com/jshttp/cookie/commit/e10042845354fea83bd8f34af72475eed1dadf5c"},{"url":"https://github.com/advisories/GHSA-pxg6-pf52-xh8x"}]}}},{"dismissedAt":null,"createdAt":"2024-10-08T21:23:06Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-5hgc-2vfp-mqvc"},{"type":"CVE","value":"CVE-2024-45230"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-45230"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/sep/03/security-releases"},{"url":"https://github.com/django/django/commit/022ab0a75c76ab2ea31dfcc5f2cf5501e378d397"},{"url":"https://github.com/django/django/commit/813de2672bd7361e9a453ab62cd6e52f96b6525b"},{"url":"https://github.com/django/django/commit/d147a8ebbdf28c17cafbbe2884f0bc57e2bf82e2"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-102.yaml"},{"url":"https://github.com/advisories/GHSA-5hgc-2vfp-mqvc"}]}}},{"dismissedAt":null,"createdAt":"2024-10-08T21:36:23Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-rrqc-c2jx-6jgv"},{"type":"CVE","value":"CVE-2024-45231"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-45231"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/forum/#%21forum/django-announce"},{"url":"https://www.djangoproject.com/weblog/2024/sep/03/security-releases"},{"url":"https://github.com/django/django/commit/3c733c78d6f8e50296d6e248968b6516c92a53ca"},{"url":"https://github.com/django/django/commit/96d84047715ea1715b4bd1594e46122b8a77b9e2"},{"url":"https://github.com/django/django/commit/bf4888d317ba4506d091eeac6e8b4f1fcc731199"},{"url":"https://github.com/advisories/GHSA-rrqc-c2jx-6jgv"}]}}},{"dismissedAt":null,"createdAt":"2024-12-06T18:46:28Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8498-2h75-472j"},{"type":"CVE","value":"CVE-2024-53907"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-53907"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/g/django-announce"},{"url":"https://www.openwall.com/lists/oss-security/2024/12/04/3"},{"url":"https://www.djangoproject.com/weblog/2024/dec/04/security-releases"},{"url":"https://lists.debian.org/debian-lts-announce/2024/12/msg00028.html"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-156.yaml"},{"url":"https://github.com/advisories/GHSA-8498-2h75-472j"}]}}},{"dismissedAt":null,"createdAt":"2024-12-06T18:47:59Z","securityVulnerability":{"severity":"HIGH","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-m9g8-fxxm-xg86"},{"type":"CVE","value":"CVE-2024-53908"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-53908"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/g/django-announce"},{"url":"https://www.openwall.com/lists/oss-security/2024/12/04/3"},{"url":"https://www.djangoproject.com/weblog/2024/dec/04/security-releases"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-157.yaml"},{"url":"https://github.com/advisories/GHSA-m9g8-fxxm-xg86"}]}}},{"dismissedAt":null,"createdAt":"2024-12-16T01:01:11Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"nanoid"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-mwcw-c2x4-8c55"},{"type":"CVE","value":"CVE-2024-55565"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-55565"},{"url":"https://github.com/ai/nanoid/pull/510"},{"url":"https://github.com/ai/nanoid/compare/3.3.7...3.3.8"},{"url":"https://github.com/ai/nanoid/releases/tag/5.0.9"},{"url":"https://github.com/advisories/GHSA-mwcw-c2x4-8c55"}]}}},{"dismissedAt":null,"createdAt":"2025-01-14T16:22:56Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-8498-2h75-472j"},{"type":"CVE","value":"CVE-2024-53907"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-53907"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/g/django-announce"},{"url":"https://www.openwall.com/lists/oss-security/2024/12/04/3"},{"url":"https://www.djangoproject.com/weblog/2024/dec/04/security-releases"},{"url":"https://lists.debian.org/debian-lts-announce/2024/12/msg00028.html"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-156.yaml"},{"url":"https://github.com/advisories/GHSA-8498-2h75-472j"}]}}},{"dismissedAt":null,"createdAt":"2025-01-14T17:00:13Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-m9g8-fxxm-xg86"},{"type":"CVE","value":"CVE-2024-53908"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-53908"},{"url":"https://docs.djangoproject.com/en/dev/releases/security"},{"url":"https://groups.google.com/g/django-announce"},{"url":"https://www.openwall.com/lists/oss-security/2024/12/04/3"},{"url":"https://www.djangoproject.com/weblog/2024/dec/04/security-releases"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-157.yaml"},{"url":"https://github.com/advisories/GHSA-m9g8-fxxm-xg86"}]}}}]},"grade":"E"}]}