{"totalCount":38,"grade":"E","repositories":[null,null,{"url":"https://github.com/MTES-MCT/adock-api","vulnerabilityAlerts":{"totalCount":38,"nodes":[{"dismissedAt":null,"createdAt":"2023-07-16T16:20:55Z","securityVulnerability":{"severity":"HIGH","package":{"name":"sqlparse"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-p5w8-wqhj-9hhf"},{"type":"CVE","value":"CVE-2021-32839"}],"references":[{"url":"https://github.com/andialbrecht/sqlparse/security/advisories/GHSA-p5w8-wqhj-9hhf"},{"url":"https://github.com/andialbrecht/sqlparse/commit/8238a9e450ed1524e40cb3a8b0b3c00606903aeb"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2021-32839"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/sqlparse/PYSEC-2021-333.yaml"},{"url":"https://securitylab.github.com/advisories/GHSL-2021-107-andialbrecht-sqlparse"},{"url":"https://github.com/advisories/GHSA-p5w8-wqhj-9hhf"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:56Z","securityVulnerability":{"severity":"HIGH","package":{"name":"ipython"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-pq7m-3gw7-gq5x"},{"type":"CVE","value":"CVE-2022-21699"}],"references":[{"url":"https://github.com/ipython/ipython/security/advisories/GHSA-pq7m-3gw7-gq5x"},{"url":"https://github.com/ipython/ipython/commit/46a51ed69cdf41b4333943d9ceeb945c4ede5668"},{"url":"https://ipython.readthedocs.io/en/stable/whatsnew/version8.html#ipython-8-0-1-cve-2022-21699"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-21699"},{"url":"https://lists.debian.org/debian-lts-announce/2022/01/msg00021.html"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/ipython/PYSEC-2022-12.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CRQRTWHYXMLDJ572VGVUZMUPEOTPM3KB"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DZ7LVZBB4D7KVSFNEQUBEHFO3JW6D2ZK"},{"url":"https://github.com/ipython/ipython/commit/5fa1e409d2dc126c456510c16ece18e08b524e5b"},{"url":"https://github.com/ipython/ipython/commit/67ca2b3aa9039438e6f80e3fccca556f26100b4d"},{"url":"https://github.com/ipython/ipython/commit/a06ca837273271b4acb82c29be97c0b6d12a30ea"},{"url":"https://github.com/advisories/GHSA-pq7m-3gw7-gq5x"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:56Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w24h-v9qh-8gxj"},{"type":"CVE","value":"CVE-2022-28347"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-28347"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"http://www.openwall.com/lists/oss-security/2022/04/11/1"},{"url":"https://github.com/django/django/commit/6723a26e59b0b5429a0c5873941e01a2e1bdbb81"},{"url":"https://github.com/advisories/GHSA-w24h-v9qh-8gxj"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-191.yaml"},{"url":"https://www.debian.org/security/2022/dsa-5254"},{"url":"https://github.com/django/django/commit/00b0fc50e1738c7174c495464a5ef069408a4402"},{"url":"https://github.com/django/django/commit/29a6c98b4c13af82064f993f0acc6e8fafa4d3f5"},{"url":"https://github.com/django/django/commit/9e19accb6e0a00ba77d5a95a91675bf18877c72d"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI"},{"url":"https://www.djangoproject.com/weblog/2022/apr/11/security-releases"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:56Z","securityVulnerability":{"severity":"CRITICAL","package":{"name":"Django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-2gwj-7jmv-h26r"},{"type":"CVE","value":"CVE-2022-28346"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-28346"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"http://www.openwall.com/lists/oss-security/2022/04/11/1"},{"url":"https://lists.debian.org/debian-lts-announce/2022/04/msg00013.html"},{"url":"https://github.com/django/django/commit/93cae5cb2f9a4ef1514cf1a41f714fef08005200"},{"url":"https://github.com/advisories/GHSA-2gwj-7jmv-h26r"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-190.yaml"},{"url":"https://www.debian.org/security/2022/dsa-5254"},{"url":"https://github.com/django/django/commit/2044dac5c6968441be6f534c4139bcf48c5c7e48"},{"url":"https://github.com/django/django/commit/2c09e68ec911919360d5f8502cefc312f9e03c5d"},{"url":"https://github.com/django/django/commit/800828887a0509ad1162d6d407e94d8de7eafc60"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI"},{"url":"https://security.netapp.com/advisory/ntap-20220609-0002"},{"url":"https://www.djangoproject.com/weblog/2022/apr/11/security-releases"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"HIGH","package":{"name":"pyjwt"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-ffqj-6fqr-9h24"},{"type":"CVE","value":"CVE-2022-29217"}],"references":[{"url":"https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-29217"},{"url":"https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc"},{"url":"https://github.com/jpadilla/pyjwt/releases/tag/2.4.0"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/pyjwt/PYSEC-2022-202.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO"},{"url":"https://github.com/advisories/GHSA-ffqj-6fqr-9h24"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-qrw5-5h28-6cmg"},{"type":"CVE","value":"CVE-2022-41323"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-41323"},{"url":"https://github.com/django/django/commit/5b6b257fa7ec37ff27965358800c67e2dd11c924"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2022-304.yaml"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://github.com/django/django/commit/23f0093125ac2e553da6c1b2f9988eb6a3dd2ea1"},{"url":"https://github.com/django/django/commit/9d656ea51d9ea7105c0c0785783ac29d426a7d25"},{"url":"https://docs.djangoproject.com/en/4.0/releases/security"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FKYVMMR7RPM6AHJ2SBVM2LO6D3NGFY7B"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VZS4G6NSZWPTVXMMZHJOJVQEPL3QTO77"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YJB6FUBBLVKKG655UMTLQNN6UQ6EDLSP"},{"url":"https://security.netapp.com/advisory/ntap-20221124-0001"},{"url":"https://www.djangoproject.com/weblog/2022/oct/04/security-releases"},{"url":"https://github.com/advisories/GHSA-qrw5-5h28-6cmg"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"HIGH","package":{"name":"py"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-w596-4wvx-j9j6"},{"type":"CVE","value":"CVE-2022-42969"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-42969"},{"url":"https://github.com/pytest-dev/py/issues/287"},{"url":"https://github.com/pytest-dev/py/blob/cb87a83960523a2367d0f19226a73aed4ce4291d/py/_path/svnurl.py#L316"},{"url":"https://github.com/pytest-dev/py/issues/288"},{"url":"https://github.com/pytest-dev/pytest/issues/10392"},{"url":"https://news.ycombinator.com/item?id=34163710"},{"url":"https://pypi.org/project/py"},{"url":"https://github.com/advisories/GHSA-w596-4wvx-j9j6"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/py/PYSEC-2022-42969.yaml"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"certifi"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-43fp-rhv2-5gv8"},{"type":"CVE","value":"CVE-2022-23491"}],"references":[{"url":"https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8"},{"url":"https://github.com/certifi/python-certifi/commit/9e9e840925d7b8e76c76fdac1fab7e6e88c1c3b8"},{"url":"https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2022-23491"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2022-42986.yaml"},{"url":"https://security.netapp.com/advisory/ntap-20230223-0010"},{"url":"https://github.com/advisories/GHSA-43fp-rhv2-5gv8"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:57Z","securityVulnerability":{"severity":"HIGH","package":{"name":"django"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-q2jf-h9jm-m7p4"},{"type":"CVE","value":"CVE-2023-23969"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-23969"},{"url":"https://lists.debian.org/debian-lts-announce/2023/02/msg00000.html"},{"url":"https://groups.google.com/forum/#!forum/django-announce"},{"url":"https://github.com/django/django/commit/4452642f193533e288a52c02efb5bbc766a68f95"},{"url":"https://github.com/django/django/commit/9d7bd5a56b1ce0576e8e07a8001373576d277942"},{"url":"https://github.com/django/django/commit/c7e0151fdf33e1b11d488b6f67b94fdf3a30614a"},{"url":"https://docs.djangoproject.com/en/4.1/releases/security"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HWY6DQWRVBALV73BPUVBXC3QIYUM24IK"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LTZVAKU5ALQWOKFTPISE257VCVIYGFQI"},{"url":"https://security.netapp.com/advisory/ntap-20230302-0007"},{"url":"https://www.djangoproject.com/weblog/2023/feb/01/security-releases"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2023-12.yaml"},{"url":"https://github.com/advisories/GHSA-q2jf-h9jm-m7p4"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:58Z","securityVulnerability":{"severity":"HIGH","package":{"name":"sentry-sdk"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-29pr-6jr8-q5jm"},{"type":"CVE","value":"CVE-2023-28117"}],"references":[{"url":"https://github.com/getsentry/sentry-python/security/advisories/GHSA-29pr-6jr8-q5jm"},{"url":"https://github.com/getsentry/sentry-python/pull/1842"},{"url":"https://github.com/getsentry/sentry-python/releases/tag/1.14.0"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-28117"},{"url":"https://github.com/advisories/GHSA-29pr-6jr8-q5jm"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:58Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"sqlparse"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-rrm6-wvj7-cwh2"},{"type":"CVE","value":"CVE-2023-30608"}],"references":[{"url":"https://github.com/andialbrecht/sqlparse/security/advisories/GHSA-rrm6-wvj7-cwh2"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-30608"},{"url":"https://github.com/andialbrecht/sqlparse/commit/c457abd5f097dd13fb21543381e7cfafe7d31cfb"},{"url":"https://github.com/andialbrecht/sqlparse/commit/e75e35869473832a1eb67772b1adfee2db11b85a"},{"url":"https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS"},{"url":"https://lists.debian.org/debian-lts-announce/2023/05/msg00017.html"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/sqlparse/PYSEC-2023-87.yaml"},{"url":"https://github.com/advisories/GHSA-rrm6-wvj7-cwh2"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:58Z","securityVulnerability":{"severity":"HIGH","package":{"name":"pymdown-extensions"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-jh85-wwv9-24hv"},{"type":"CVE","value":"CVE-2023-32309"}],"references":[{"url":"https://github.com/facelessuser/pymdown-extensions/security/advisories/GHSA-jh85-wwv9-24hv"},{"url":"https://github.com/facelessuser/pymdown-extensions/commit/b7bb4878d6017c03c8dc97c42d8d3bb6ee81db9d"},{"url":"https://github.com/facelessuser/pymdown-extensions/releases/tag/10.0"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-32309"},{"url":"https://github.com/advisories/GHSA-jh85-wwv9-24hv"}]}}},{"dismissedAt":null,"createdAt":"2023-07-16T16:20:58Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"requests"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-j8r2-6x86-q33q"},{"type":"CVE","value":"CVE-2023-32681"}],"references":[{"url":"https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q"},{"url":"https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-32681"},{"url":"https://github.com/psf/requests/releases/tag/v2.31.0"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2023-74.yaml"},{"url":"https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html"},{"url":"https://security.gentoo.org/glsa/202309-08"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ"},{"url":"https://github.com/advisories/GHSA-j8r2-6x86-q33q"}]}}},{"dismissedAt":null,"createdAt":"2023-10-03T00:20:46Z","securityVulnerability":{"severity":"HIGH","package":{"name":"urllib3"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-v845-jxx5-vc9f"},{"type":"CVE","value":"CVE-2023-43804"}],"references":[{"url":"https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f"},{"url":"https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb"},{"url":"https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-43804"},{"url":"https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-192.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ"},{"url":"https://security.netapp.com/advisory/ntap-20241213-0007"},{"url":"https://www.vicarius.io/vsociety/posts/cve-2023-43804-urllib3-vulnerability-3"},{"url":"https://github.com/advisories/GHSA-v845-jxx5-vc9f"}]}}},{"dismissedAt":null,"createdAt":"2023-10-26T15:51:33Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"urllib3"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-g4mx-q9vg-27p4"},{"type":"CVE","value":"CVE-2023-45803"}],"references":[{"url":"https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4"},{"url":"https://github.com/urllib3/urllib3/commit/4e50fbc5db74e32cabd5ccc1ab81fc103adfe0b3"},{"url":"https://github.com/urllib3/urllib3/commit/b594c5ceaca38e1ac215f916538fb128e3526a36"},{"url":"https://github.com/urllib3/urllib3/releases/tag/1.26.18"},{"url":"https://github.com/urllib3/urllib3/releases/tag/2.0.7"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2023-45803"},{"url":"https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9"},{"url":"https://www.rfc-editor.org/rfc/rfc9110.html#name-get"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-212.yaml"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX"},{"url":"https://github.com/advisories/GHSA-g4mx-q9vg-27p4"}]}}},{"dismissedAt":null,"createdAt":"2024-01-11T21:58:12Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"jinja2"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-h5c8-rqwp-cp95"},{"type":"CVE","value":"CVE-2024-22195"}],"references":[{"url":"https://github.com/pallets/jinja/security/advisories/GHSA-h5c8-rqwp-cp95"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-22195"},{"url":"https://github.com/pallets/jinja/commit/716795349a41d4983a9a4771f7d883c96ea17be7"},{"url":"https://github.com/pallets/jinja/releases/tag/3.1.3"},{"url":"https://lists.debian.org/debian-lts-announce/2024/01/msg00010.html"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5XCWZD464AJJJUBOO7CMPXQ4ROBC6JX2"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DELCVUUYX75I5K4Q5WMJG4MUZJA6VAIP"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O7YWRBX6JQCWC2XXCTZ55C7DPMGICCN3"},{"url":"https://github.com/advisories/GHSA-h5c8-rqwp-cp95"}]}}},{"dismissedAt":null,"createdAt":"2024-03-20T18:41:22Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"black"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-fj7x-q9j7-g6q6"},{"type":"CVE","value":"CVE-2024-21503"}],"references":[{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-21503"},{"url":"https://github.com/psf/black/commit/f00093672628d212b8965a8993cee8bedf5fe9b8"},{"url":"https://github.com/psf/black/releases/tag/24.3.0"},{"url":"https://security.snyk.io/vuln/SNYK-PYTHON-BLACK-6256273"},{"url":"https://github.com/pypa/advisory-database/tree/main/vulns/black/PYSEC-2024-48.yaml"},{"url":"https://github.com/advisories/GHSA-fj7x-q9j7-g6q6"}]}}},{"dismissedAt":null,"createdAt":"2024-05-06T21:13:07Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"Jinja2"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-h75v-3vvj-5mfj"},{"type":"CVE","value":"CVE-2024-34064"}],"references":[{"url":"https://github.com/pallets/jinja/security/advisories/GHSA-h75v-3vvj-5mfj"},{"url":"https://github.com/pallets/jinja/commit/0668239dc6b44ef38e7a6c9f91f312fd4ca581cb"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-34064"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/567XIGSZMABG6TSMYWD7MIYNJSUQQRUC"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/GCLF44KY43BSVMTE6S53B4V5WP3FRRSE"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SSCBHIL6BYKR5NRCBXP4XMP2CEEKGFVS"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZALNWE3TXPPHVPSI3AZ5CTMSTAVN5UMS"},{"url":"https://github.com/advisories/GHSA-h75v-3vvj-5mfj"}]}}},{"dismissedAt":null,"createdAt":"2024-05-20T23:08:16Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"requests"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-9wx4-h78v-vm56"},{"type":"CVE","value":"CVE-2024-35195"}],"references":[{"url":"https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56"},{"url":"https://github.com/psf/requests/pull/6655"},{"url":"https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-35195"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q"},{"url":"https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ"},{"url":"https://github.com/advisories/GHSA-9wx4-h78v-vm56"}]}}},{"dismissedAt":null,"createdAt":"2024-06-17T22:20:44Z","securityVulnerability":{"severity":"MODERATE","package":{"name":"urllib3"},"advisory":{"identifiers":[{"type":"GHSA","value":"GHSA-34jh-p97f-mpxf"},{"type":"CVE","value":"CVE-2024-37891"}],"references":[{"url":"https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf"},{"url":"https://nvd.nist.gov/vuln/detail/CVE-2024-37891"},{"url":"https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468"},{"url":"https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e"},{"url":"https://github.com/advisories/GHSA-34jh-p97f-mpxf"}]}}}]},"grade":"E"}]}